{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openwhistle.fullname" . }}-secret
  labels:
    {{- include "openwhistle.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ required "secrets.secretKey is required" .Values.secrets.secretKey | quote }}
  DATABASE_URL: {{ required "secrets.databaseUrl is required" .Values.secrets.databaseUrl | quote }}
  REDIS_URL: {{ required "secrets.redisUrl is required" .Values.secrets.redisUrl | quote }}
  {{- if .Values.secrets.smtpPassword }}
  NOTIFY_SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.webhookSecret }}
  NOTIFY_WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.s3SecretAccessKey }}
  S3_SECRET_ACCESS_KEY: {{ .Values.secrets.s3SecretAccessKey | quote }}
  {{- end }}
  {{- if .Values.secrets.ldapBindPassword }}
  LDAP_BIND_PASSWORD: {{ .Values.secrets.ldapBindPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.oidcClientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  {{- end }}
{{- end }}
